WebApp/Controllers/ExtruderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Abstract;
using DAL.Models;
using DAL.UnitOfWork;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class ExtruderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;


        public ExtruderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Extruder
        public ActionResult Index()
        {
            //var extruders = _unitOfWork.ExtruderRepository.GetAll();
            var extruders = _unitOfWork.ExtruderRepository.GetAll();
            return View(extruders);
        }

        // GET: Extruder/Details/5
        public ActionResult Details(string id)
        {
            var extruder = _unitOfWork.ExtruderRepository.Get(id);
            return View(extruder);
        }

        // GET: Extruder/Create
        public ActionResult Create()
        {
            Extruder extruder = new Extruder();
            return View(extruder);
        }

        // POST: Extruder/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Extruder extruder)
        { 

            if(ModelState.IsValid)
            {
                _unitOfWork.ExtruderRepository.Add(extruder);
                return RedirectToAction(nameof(Index));
            }

            return View();

        }

        // GET: Extruder/Edit/5
        public ActionResult Edit(string id)
        {
            var extruder = _unitOfWork.ExtruderRepository.Get(id);
            return View(extruder);
        }

        // POST: Extruder/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, Extruder extruder)
        {
            try
            {
                _unitOfWork.ExtruderRepository.Update(x => x.Id == extruder.Id, extruder);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Extruder/Delete/5
        public ActionResult Delete(string id)
        {
            _unitOfWork.ExtruderRepository.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        // POST: Extruder/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApp/Controllers/ReaderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL.Models;
using DAL.UnitOfWork;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class ReaderController : Controller
    {
        //private readonly IReaderService _readerService;
        private readonly IUnitOfWork _unitOfWork;


        public ReaderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Reader
        public IActionResult Index()
        {
            var reader = _unitOfWork.ReaderRepository.GetAll();
            return View(reader);
        }

        // GET: Reader/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Reader/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Reader reader)
        {
            if (ModelState.IsValid)
            {
                reader.ReaderNumber = "ABC111"; //dla testu
                if (reader.ReaderNumber != null)
                {
                    _unitOfWork.ReaderRepository.Add(reader);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("Exist", "Taki czytnik jest już w bazie! Podepnij inny!");
                    return View(reader);
                }
            }
            else
            {
                return View(reader);
            }
        }

        // GET: Reader/Edit/5
        public IActionResult Edit(string id)
        {
            return View();
        }

        // POST: Reader/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, Reader reader)
        {
            try
            {
                _unitOfWork.ReaderRepository.Update(x => x.Id == reader.Id, reader);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Reader/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return Problem();
        //    }
        //    var details = _readerService.Get((int)id);

        //    return View(details);
        //}


        //[ValidateAntiForgeryToken]
        public IActionResult Delete(string id)
        {
            if (id != null)
            {
                _unitOfWork.ReaderRepository.Delete(id);
                return RedirectToAction(nameof(Index));

            }
            return RedirectToAction(nameof(Index));

        }

        //public IActionResult Details()
        //{
        //    return View();
        //}
        public IActionResult Details(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            Reader reader = _unitOfWork.ReaderRepository.Get(id);
            if (reader == null)
            {
                return NotFound();
            }
            return View(reader);

        }

    }
}

WebApp/Controllers/WorkerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL.Models;
using DAL.UnitOfWork;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class WorkerController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public WorkerController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        // GET: Worker
        public ActionResult Index()
        {
            var workers = _unitOfWork.WorkerRepository.GetAll();
            return View(workers);
        }

        // GET: Worker/Details/5
        public ActionResult Details(string id)
        {
            var worker = _unitOfWork.WorkerRepository.Get(id);
            return View(worker);
        }

        // GET: Worker/Create
        public ActionResult Create()
        {
            Worker worker = new Worker();
            return View(worker);
        }

        // POST: Worker/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Worker worker)
        {
            if(ModelState.IsValid)
            {
                _unitOfWork.WorkerRepository.Add(worker);
                return RedirectToAction(nameof(Index));                
            }
            return View();
        }

        // GET: Worker/Edit/5
        public ActionResult Edit(string id)
        {
            var worker = _unitOfWork.WorkerRepository.Get(id);
            return View(worker);
        }

        // POST: Worker/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, Worker worker)
        {
            try
            {
                _unitOfWork.WorkerRepository.Update(x => x.Id == worker.Id, worker);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Worker/Delete/5
        public ActionResult Delete(string id)
        {
            var worker = _unitOfWork.WorkerRepository.Get(id);
            return View(worker);
        }

        // POST: Worker/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
    .dropbtn {
      background-color: #333;
      color: white;
      padding: 16px;
      font-size: 16px;
      border: none;
    }

    /* The container <div> - needed to position the dropdown content */
    .dropdown {
      position: relative;
      display: inline-block;
    }

    /* Dropdown Content (Hidden by Default) */
    .dropdown-content {
      display: none;
      position: absolute;
      background-color: #f1f1f1;
      min-width: 160px;
      box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
      z-index: 1;
    }

    /* Links inside the dropdown */
    .dropdown-content a {
      color: black;
      padding: 12px 16px;
      text-decoration: none;
      display: block;
    }

    /* Change color of dropdown links on hover */
    .dropdown-content a:hover {background-color: #ddd;}

    /* Show the dropdown menu on hover */
    .dropdown:hover .dropdown-content {display: block;}

    /* Change the background color of the dropdown button when the dropdown content is shown */
    .dropdown:hover .dropbtn {background-color: #333;}
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reader" asp-action="Index">Reader</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Registration">User</a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li>
                                <a asp-area="" asp-controller="User" asp-action="Login">
                                    <span class="glyphicon glyphicon-user"></span>
                                    Zaloguj się
                                </a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("SuperAdmin") || User.IsInRole("Admin"))
                            {
                                <div class="dropdown">
                                    <button class="dropbtn">AdminMenu</button>
                                    <div class="dropdown-content">
                                        <a asp-area="" asp-controller="Worker" asp-action="Index">Pracownicy</a>
                                        <a asp-area="" asp-controller="Extruder" asp-action="Index">Wytłaczarki</a>
                                        <a asp-area="" asp-controller="Reader" asp-action="Index">Czytniki</a>
                                    </div>
                                </div>
                            }
                            <li style="float: right">
                                <h4 style="color:black; margin-top:16px">
                                    Witaj @User.Claims.SingleOrDefault(x => x.Type == ClaimTypes.GivenName)?.Value!
                                </h4>
                                <a asp-controller="User" asp-action="Logout">
                                    <span class="glyphicon glyphicon-log-out"></span>
                                    Wyloguj
                                </a>
                            </li>
                            <li style="float: right;">
                            </li>

                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <partial name="_CookieConsentPartial" />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap-select/js/bootstrap-select.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>